version: "3"
services:
  redis:
    image: redis:7-alpine
    restart: unless-stopped
    command: ["redis-server", "/etc/redis/redis.conf"]
    ports:
      - 6379:6379
    volumes:
      - ./redis_data:/data
      - ./redis.conf:/etc/redis/redis.conf

  api:
    depends_on:
      - redis
      - pocketbase
    image: developomp/exyleio-api:latest
    restart: unless-stopped
    ports:
      - 80:80
    volumes:
      - ./api_log:/log

  discord-bot:
    depends_on:
      - api
    image: developomp/exyleio-discord-bot:latest
    environment:
      DISCORD_BOT_TOKEN: ${DISCORD_BOT_TOKEN}
      DISCORD_BOT_ID: ${DISCORD_BOT_ID}
