version: "3"
services:
  redis:
    image: redis/redis-stack-server:latest
    restart: unless-stopped
    expose:
      - 6379
    volumes:
      - ./redis_stack_data/:/data

  api:
    depends_on:
      - redis
    image: developomp/exyleio-api:latest
    restart: unless-stopped
    extra_hosts:
      - host.docker.internal:host-gateway
    expose:
      - 8000
    volumes:
      - ./api_log:/log
      - ./serviceAccountKey.json:/app/serviceAccountKey.json

  discord-bot:
    depends_on:
      - api
    image: developomp/exyleio-discord-bot:latest
    environment:
      DISCORD_BOT_TOKEN: ${DISCORD_BOT_TOKEN}
      DISCORD_BOT_ID: ${DISCORD_BOT_ID}

  web:
    depends_on:
      - api
    image: developomp/exyleio-web:latest
    expose:
      - 3000

  nginx:
    depends_on:
      - api
      - web
    image: nginx:latest
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx_data/certbot/conf:/etc/letsencrypt 
      - ./nginx_data/certbot/www:/var/www/certbot
    # reload nginx every 24h to refresh SSL certificate
    command: "/bin/sh -c 'while :; do sleep 24h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"

  # SSL certificate renewal
  certbot:
    image: certbot/certbot
    restart: unless-stopped
    volumes:
      - ./nginx_data/certbot/conf:/etc/letsencrypt 
      - ./nginx_data/certbot/www:/var/www/certbot
    # renew SSL certificate every 48h
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 48h & wait $${!}; done;'"
