version: "3"
services:
  redis:
    image: redis/redis-stack-server:latest
    restart: unless-stopped
    expose:
      - 6379
    volumes:
      - ./redis_stack_data/:/data

  api:
    depends_on:
      - redis
    image: developomp/exyleio-api:latest
    restart: unless-stopped
    extra_hosts:
      - host.docker.internal:host-gateway
    expose:
      - 8000
    volumes:
      - ./api_log:/log
      - ./serviceAccountKey.json:/app/serviceAccountKey.json

  discord-bot:
    depends_on:
      - api
    image: developomp/exyleio-discord-bot:latest
    environment:
      DISCORD_BOT_TOKEN: ${DISCORD_BOT_TOKEN}
      DISCORD_BOT_ID: ${DISCORD_BOT_ID}

  web:
    depends_on:
      - api
    image: developomp/exyleio-web:latest
    expose:
      - 3000

  nginx:
    depends_on:
      - web
    image: nginx:latest
    restart: unless-stopped
    ports:
      - 80:80 # only used for testing. Not actually used in production.
      - 443:443
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
